version: "3.9"
services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    env_file:
      - ./nginx-files/nginx-certbot.env
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./nginx-files:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
    restart: always
  crlw-app-database:
    image: mysql:latest
    container_name: database
    # build: ./database
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=crlw_database
      - MYSQL_ROOT_PASSWORD=password
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 500M
  crlw-app-backend:
    image: ladymeek/crlw-backend-do:sha-43e08dc
    container_name: api
    # build: ./backend
    expose:
      - "8000"
    restart: always
    depends_on:
      - "crlw-app-database"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./backend/drf_jwt_backend/local_settings.py:/user/src/app/drf_jwt_backend/local_settings.py
  crlw-app-frontend:
    image: ladymeek/crlw-frontend-do:sha-83df13f
    container_name: frontend
    # build: ./frontend
    expose:
      - "80"
    depends_on:
      - "crlw-app-backend"
    restart: always
volumes:
  db-data:
  nginx_secrets:
