# Generated by Django 4.2.2 on 2023-07-02 20:21

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description_text', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to=properties.models.upload_to)),
                ('youtube_link', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
